### ISSUE TITLE
opkg update does not work anymore

### ISSUE THREAD

**Issue by touran-dot** [freifunk-stuttgart/site-ffs#37]
I intended to add to my TL-WR841N (and other installations) vn-stat per "opkg install vnstat" on the console. This does not work.

Affected is:

root@my-841:/etc/opkg# cat /lib/gluon/gluon-version
v2016.2.7
root@my-841:/etc/opkg# cat /lib/gluon/release
1.3+2017-09-13-g.d722c26-s.b0e5e48
root@my-841:/etc/opkg#

Packages from http://downloads.openwrt.org/ cannot be downloaded.

The ressources are defined in/etc/opkg/distfeeds.conf as follows:

src/gz chaos_calmer_base http://downloads.openwrt.org/chaos_calmer/15.05.1/ar71xx/generic/packages/base
src/gz chaos_calmer_packages http://downloads.openwrt.org/chaos_calmer/15.05.1/ar71xx/generic/packages/packages
src/gz chaos_calmer_luci http://downloads.openwrt.org/chaos_calmer/15.05.1/ar71xx/generic/packages/luci
src/gz chaos_calmer_routing http://downloads.openwrt.org/chaos_calmer/15.05.1/ar71xx/generic/packages/routing
src/gz chaos_calmer_telephony http://downloads.openwrt.org/chaos_calmer/15.05.1/ar71xx/generic/packages/telephony
src/gz chaos_calmer_management http://downloads.openwrt.org/chaos_calmer/15.05.1/ar71xx/generic/packages/management

Root cause of the problems is, that the packages are now available under http://archive.openwrt.org/ .

I manually modified the base URL to http://archive.openwrt.org/ , then opkg works as expected.

Please consider the modified URL for the next FW update.

**Comment by dadosch** [comment]
`downloads.openwrt.org` does now do a redirect to `archive.openwrt.org` at least for subdirectory `/chaos_calmer/`

I just tried `opkg update` on my TL1043ND and it works fine, without any modifications.
